config/routes.rb
Rails.application.routes.draw do

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  #カスタマー用
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
}
  #業者用
  devise_for :traders, skip: [:passwords], controllers: {
  registrations: "trader/registrations",
  sessions: "trader/sessions"
}

  root to: "homes#top"

  namespace :customer do
    resources :traders, only: [:index, :show]
  end

  scope module: :trader do
    resources :traders, only: [:index, :show, :edit, :update, :destroy] do
      resources :posts, only: [:new, :create, :destroy]
    end
    resources :schedules, only: [:index, :create, :destroy]
    resources :areas, only: [:index, :create, :destroy, :destroy]
    resources :machines, only: [:index, :create, :destroy]
    get "home" => "homes#top", as: 'pro'
  end

  get "admin/home" => "admin/homes#top", as: 'admin'
  namespace :admin do
    resources :traders, only: [:index, :show]
    resources :customers, only: [:index]
  end

  devise_scope :customer do
    post "customers/guest_sign_in", to: "customer/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/trader.rb
class Trader < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trader_areas, dependent: :destroy
  has_many :areas, through: :trader_areas

  has_many :trader_machines, dependent: :destroy
  has_many :machines, through: :trader_machines

  has_many :posts, dependent: :destroy

  has_many :schedules, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/AC.png')
    profile_image.attach(io: File.open(file_path), filename: 'no-image.png', content_type: 'image/png')
  end
    profile_image
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/traders_controller.rb
class Admin::TradersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @traders = Trader.all.page(params[:page]).per(7)
  end

  def show
    @trader = Trader.find(params[:id])
    #日程(start_time)を日付順に並び替え
    @schedules = @trader.schedules.where(start_time: Time.zone.now.beginning_of_day..).order(start_time: :asc)
    @posts = @trader.posts
  end

end

app/controllers/customer/traders_controller.rb
class Customer::TradersController < ApplicationController

  def index
    @areas = Area.all
    @machines = Machine.all
    #以下、検索機能
    @traders = Trader.all
    @traders = @traders.joins(:areas).merge(Area.where(id: params[:area_ids].presence)) if params[:area_ids].present?
    @traders = @traders.joins(:machines).merge(Machine.where(id: params[:machine_ids].presence)) if params[:machine_ids].present?
    @traders = @traders.joins(:schedules).merge(Schedule.where(start_time: (params[:start_time].to_datetime)..(params[:start_time].to_datetime.end_of_day))) if params[:start_time].present?
  end

  def show
    @trader = Trader.find(params[:id])
    #日程(start_time)を日付順に並び替え
    @schedules = @trader.schedules.where(start_time: Time.zone.now.beginning_of_day..).order(start_time: :asc)
    @posts = @trader.posts
  end

  private

  def trader_params
    params.require(:trader).permit(:company_name, :company_name_kana, :post_code, :address, :telephone_number, :compatible_machine, :public_relations, :profile_image, :start_time, area_ids: [], machine_ids: [])
  end

end

app/controllers/trader/areas_controller.rb
class Trader::AreasController < ApplicationController
  before_action :authenticate_admin!

  def create
    @area = Area.new(area_params)
    @areas = Area.all
    @area.save
    redirect_to request.referer
  end

  def index
    @areas = Area.all
    @area = Area.new
  end

  def destroy
    @areas = Area.all
    @area = Area.find(params[:id])
    @area.destroy
    redirect_to request.referer
  end

  private

  def area_params
    params.require(:area).permit(:compatible_area)
  end

end

app/controllers/trader/confirmations_controller.rb
# frozen_string_literal: true

class Trader::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/trader/homes_controller.rb
class Trader::HomesController < ApplicationController

  def top
    #カスタマーがログインしている場合にのみ、カスタマーをログアウトさせる
    sign_out(current_customer) if customer_signed_in?
  end

end

app/controllers/trader/machines_controller.rb
class Trader::MachinesController < ApplicationController
  before_action :authenticate_admin!

  def create
    @machine = Machine.new(machine_params)
    @machines = Machine.all
    @machine.save
    redirect_to request.referer
  end

  def index
    @machines = Machine.all
    @machine = Machine.new
  end

  def destroy
    @machines = Machine.all
    @machine = Machine.find(params[:id])
    @machine.destroy
    redirect_to request.referer
  end

  private

  def machine_params
    params.require(:machine).permit(:possible_machine)
  end

end

app/controllers/trader/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Trader::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/trader/passwords_controller.rb
# frozen_string_literal: true

class Trader::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/trader/posts_controller.rb
class Trader::PostsController < ApplicationController
  before_action :authenticate_customer!

  def new
    @comment = Post.new
    @rating = Post.new
    @trader = Trader.find(params[:trader_id])
  end

  def create
    trader = Trader.find(params[:trader_id])
    post = Post.new(post_params)
    post.customer_id = current_customer.id
    post.trader_id = trader.id
    if post.save
      redirect_to  customer_trader_path(trader.id)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    if admin_signed_in?
      redirect_to admin_trader_path(@post.trader)
    else
      redirect_to customer_trader_path(@post.trader)
    end
  end

  private

  def post_params
    params.require(:post).permit(:comment, :rating)
  end

end

app/controllers/trader/registrations_controller.rb
# frozen_string_literal: true

class Trader::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:company_name, :company_name_kana, :post_code, :address, :telephone_number, :compatible_machine, :public_relations])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    traderid = resource.id
    trader_path(traderid)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/trader/schedules_controller.rb
class Trader::SchedulesController < ApplicationController
  before_action :authenticate_trader!

  def create
    #日程(start_time)未入力に対するif文
    if params[:start_time].present?
      @schedule = Schedule.new(start_time: params[:start_time], trader_id: current_trader.id)
    if !Schedule.where(:start_time => @schedule.start_time.to_date.beginning_of_day..@schedule.start_time.to_date.end_of_day,:trader_id => current_trader.id).exists?
      @schedule.save
    end
    end
    redirect_to request.referer
  end

  def index
    @schedules = current_trader.schedules
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to request.referer
  end


private

  def schedule_params
    params.require(:schedule).permit(:trader_id, :start_time)
  end

end

app/controllers/trader/sessions_controller.rb
# frozen_string_literal: true

class Trader::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    traderid = resource.id
    trader_path(traderid)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/trader/traders_controller.rb
class Trader::TradersController < ApplicationController
  before_action :authenticate_trader!
  before_action :is_matching_login_trader, only: [:edit, :update]

  def index
    @areas = Area.all
    @machines = Machine.all
    @traders = Trader.all.page(params[:page]).per(7)
  end

  def show
    @trader = Trader.find(params[:id])
    #日程(start_time)を日付順に並び替え
    @schedules = @trader.schedules.where(start_time: Time.zone.now.beginning_of_day..).order(start_time: :asc)
    @posts = @trader.posts
  end

  def edit
    @trader = Trader.find(params[:id])
    @areas = Area.all
    @machines = Machine.all
  end

  def update
    @trader = Trader.find(params[:id])
    @trader.update(trader_params)
    redirect_to trader_path(@trader.id)
  end

  def destroy
    @trader = Trader.find(params[:id])
    @trader.destroy
    redirect_to root_path, notice: "退会しました。"
  end

  private

  def trader_params
    params.require(:trader).permit(:company_name, :company_name_kana, :post_code, :address, :telephone_number, :compatible_machine, :public_relations, :profile_image, :start_time, area_ids: [], machine_ids: [])
  end

  def is_matching_login_trader
    trader = Trader.find(params[:id])
    unless trader.id == current_trader.id
      redirect_to traders_path
    end
  end

end

app/controllers/trader/unlocks_controller.rb
# frozen_string_literal: true

class Trader::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/trader_helper.rb
module Admin::TraderHelper
end

app/helpers/trader/areas_helper.rb
module Trader::AreasHelper
end

app/helpers/trader/homes_helper.rb
module Trader::HomesHelper
end

app/helpers/trader/machines_helper.rb
module Trader::MachinesHelper
end

app/helpers/trader/schedules_helper.rb
module Trader::SchedulesHelper
end

app/views/trader/traders/_detail.html.erb
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th scope="row">会社名</th>
            <td><%= trader.company_name %></td>
          </tr>
          <tr>
            <th scope="row">カナ</th>
            <td><%= trader.company_name_kana %></td>
          </tr>
          <tr>
            <th scope="row">郵便番号</th>
            <td>〒<%= trader.post_code %></td>
          </tr>
          <tr>
            <th scope="row">住所</th>
            <td><%= trader.address %></td>
          </tr>
          <tr>
            <th scope="row">電話番号</th>
            <td><%= trader.telephone_number %></td>
          </tr>
          <tr>
            <th scope="row">E-mail</th>
            <td><%= trader.email %></td>
          </tr>

          <tr>
            <th scope="row">対応エリア</th>
            <td><%= trader.areas.map(&:compatible_area).join(" / ") %></td>
          </tr>
          <tr>
            <th scope="row">対応機器</th>

            <td><%= trader.machines.map(&:possible_machine).join(" / ") %></td>
          </tr>
          <tr>
            <th scope="row">対応可能日</th>
            <td><%= schedules.map{|s| s.start_time.strftime("%-m月%-d日")}.join(" ／ ") %></td>
                <!--上コードは以下と同じ意味-->
                <%# @trader.schedules.each do |schedule| %>
                <%#= schedule.start_time.strftime("%m月%d日") %>
                <%# end %>
          </tr>
          <tr>
            <th scope="row">Ｐ　Ｒ</th>
            <td><%= trader.public_relations %></td>
          </tr>
        </tbody>
      </table>

app/views/trader/traders/_index.html.erb
      <h4>登録業者</h4>
      <table class="table mx-auto mt-4">
        <thead>
          <tr>
            <th>会社名</th>
            <th>対応可能エリア</th>
            <th>対応可能機器</th>
          </tr>
        </thead>
        <% traders.each do |trader| %>
        <tbody>
          <tr>
            <td><%= link_to trader.company_name, trader_path(trader) %></td>
            <td><%= trader.areas.map(&:compatible_area).join(" ／ ") %></td>
            <td><%= trader.machines.map(&:possible_machine).join(" ／ ") %></td>
          </tr>
        </tbody>
        <% end %>
      </table>

app/views/trader/traders/edit.html.erb
<div class="container mt-3">
<h2>会員登録編集</h2>
<br>
  <%= form_with model: @trader, url: trader_path, method: :patch do |f| %>
  <%= render "customer/shared/error_messages", resource: @trader %>
  <div class="row">
    <div class="col-md-2">
      <div class="form-group col-2">
        <%= image_tag @trader.get_profile_image(150, 150) %>
      </div>
    </div>
    <div class="col-md-5">
      <div class="form-group col-10">
        <%= f.label :image, "画像"%>
        <%= f.file_field :profile_image, accept: 'image/*' %>
      </div>
      <div class="form-group col-10">
        <%= f.label :company_name, "会社名" %>
        <%= f.text_field :company_name, autofocus: true ,:placeholder =>"空調職人株式会社", size: "30", class: "form-control ml-4" %>
      </div>
      <div class="form-group col-10">
        <%= f.label :company_name_kana, "カナ" %>
        <%= f.text_field :company_name_kana, :placeholder =>"クウチョウショクニン(カブ", size: "50", class: "form-control ml-4" %>
      </div>
      <div class="form-group col-5">
        <%= f.label :post_code, "郵便番号" %>
        <%= f.text_field :post_code, :placeholder =>"8888888", size: "5", class: "form-control ml-4" %>
      </div>
      <div class="form-group col-10">
        <%= f.label :address, "住所" %>
        <%= f.text_field :address, :placeholder =>"8888888", size: "50", class: "form-control ml-4" %>
      </div>
      <div class="form-group col-7">
        <%= f.label :telephone_number, "電話番号" %>
        <%= f.text_field :telephone_number, :placeholder =>"09088888888", size: "30", class: "form-control ml-4" %>
      </div>
      <div class="form-group col-8">
        <%= f.label :email %>
        <%= f.email_field :email, autocomplete: "email", :placeholder =>"888@888.com", size: "30", class: "form-control ml-4" %>
      </div>
    </div>
    <div class="col-md-5">
      <div class="form-group">
        <%= link_to "対応可能日入力",  schedules_path, class: "btn btn-outline-secondary btn-block", data: { confirm: "【確認】新規データ登録の場合は入力データが無効になります"} %>
      </div>
      <div class="form-group row mt-3">
        <%= f.label :area_ids, '対応可能エリア', class: 'col-md-7' %>
        <div class="col-md-8 border d-flex flex-row flex-wrap">
          <%= f.collection_check_boxes :area_ids, @areas, :id, :compatible_area do |b| %>
          <div class="mx-2 mt-1">
            <%= b.check_box %>
            <%= b.label %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :machine_ids, '対応可能機器', class: 'col-md-7' %>
        <div class="col-md-8 border d-flex flex-row flex-wrap">
          <%= f.collection_check_boxes :machine_ids, @machines, :id, :possible_machine do |b| %>
            <div class="mx-2 mt-1">
              <%= b.check_box %>
              <%= b.label %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="form-group row mt-3">
        <%= f.label :password_confirmation, "PR・実績・資格等" %>
        <%= f.text_area :public_relations, rows: "5", class: "w-100" %>
      </div>
      <div class="form-group mt-4">
        <%= f.submit '登   録', class: "btn btn-primary btn-block" %>
      </div>

      <div class="flex justify-around mt-4">
        <%= link_to "退会する",  trader_path, method: :delete, "data-confirm" => "OKを押すと退会処理がされます。本当によろしいですか？", class: "btn btn-danger btn-block" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/trader/traders/index.html.erb
<div class='container'>
  <div class= "row">
    <div class='col-md-8 offset-md-2'>

      <%= render 'index', traders: @traders %>

    <%= paginate @traders %>
    </div>
  </div>
</div>

app/views/trader/traders/show.html.erb
<div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <P class="nav-link active" aria-current="true"><%= @trader.company_name %></P>
      </li>
    </ul>
  </div>
  <div class="card-body">
  <h2>会社詳細</h2>
    <div class="row">
      <div class="col-md-2">
        <div class="form-group col-8">
          <%= image_tag @trader.get_profile_image(250, 250) %>
        </div>
      </div>
      <div class="col-md-10">

        <%= render 'detail', trader: @trader, schedules: @schedules %>

        <div class="flex align-center pl5">
          <%= link_to "編集する", edit_trader_path(@trader), class: "btn btn-success" if @trader == current_trader %>
        </div>
      </div>
    </div>
  </div>
    <!--♯自分の会社のレビューのみ閲覧可能-->
  <% if @trader == current_trader %>
  <div class="col mt-3">
  <h6>＜レビュー＞</h6>
    <% @posts.each do |post| %>
    <div class="card ml-5">
      <div class="card-body">
        <%= render "trader/posts/rating", post: post %>
        <div class="card-text">
          <%= post.customer.last_name %>　様
          <%= post.created_at.strftime('%Y/%m/%d') %><br>
          <%= post.comment %></tr><br>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
</div>